// Mutations enums
export enum MutationTypes {
  SET_ORDER_TABLE_DATA = 'SET_ORDER_TABLE_DATA',
  SET_QUOTE_TABLE_DATA = 'SET_QUOTE_TABLE_DATA',
  SET_INVOICE_TABLE_DATA = 'SET_INVOICE_TABLE_DATA',
  SET_PURCHASE_TABLE_DATA = 'SET_PURCHASE_TABLE_DATA',
  SET_STOCK_TAKE_TABLE_DATA = 'SET_STOCK_TAKE_TABLE_DATA',
  SET_REPORT_FILTER = 'SET_REPORT_FILTER',
  SET_DUMMY_DATA = 'SET_DUMMY_DATA',
}
