// Mutations enums
export enum MutationTypes {
  SET_CURRENT_USERDATA = 'SET_CURRENT_USERDATA',
  SET_FIREBASE_REG_TOKEN = 'SET_FIREBASE_REG_TOKEN',
  SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN',
  SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN',
  SET_ACCOUNTS = 'SET_ACCOUNTS',
  SET_ACCOUNT_SET_MODAL = 'SET_ACCOUNT_SET_MODAL',
  SET_CATEGORIES_ACCSETS = 'SET_CATEGORIES_ACCSETS',
  LOADING_CATEGORIES_ACCSETS = 'LOADING_CATEGORIES_ACCSETS',
}
