import { IAuth } from './auth';

export const state: IAuth = {
  currentUserData: {
    name: '',
    email: '',
  },
  firebaseRegToken: '',
  showAccountSetDialog: false,
  accsets: [],
  loadingCategoriesAccsets: false,
  menus: [
    {
      label: 'Home',
      name: 'home',
      url: '/home',
      subMenus: [],
      isMobile: true,
      isDesktop: true,
      expanded: false,
      separator: true,
      loading: false,
      type: 0,
    },
    {
      label: 'Categories',
      name: 'categories',
      url: '/categorynew',
      subMenus: [],
      isMobile: true,
      isDesktop: true,
      expanded: false,
      separator: true,
      loading: false,
      type: 1,
    },
    {
      label: 'Specials',
      name: 'specials',
      url: '/special-products',
      subMenus: [
        { label: 'Monthly Specials', url: '/special-products' },
        { label: 'New', url: '/new-products' },
      ],
      isMobile: true,
      isDesktop: true,
      expanded: false,
      separator: true,
      loading: false,
      type: 2,
    },
    {
      label: 'My Pantry',
      name: 'myPantry',
      url: '/my-pantry',
      subMenus: [
        { label: 'Recommended', url: '', isClick: true, name: 'recommended' },
        { label: 'Custom', url: '', isClick: true, name: 'custom' },
        { label: 'Favourites', url: '', isClick: true, name: 'favourites' },
        {
          label: 'Repeat Orders/Saved Carts',
          url: '',
          isClick: true,
          name: 'repeatOrders',
        },
        {
          label: 'Standing Orders',
          url: '',
          isClick: true,
          name: 'viewStandingOrders',
        },
      ],
      isMobile: true,
      isDesktop: true,
      expanded: false,
      separator: true,
      loading: false,
      type: 3,
    },
    {
      label: 'My Account',
      name: 'myAccount',
      url: '/my-account',
      subMenus: [],
      isMobile: true,
      isDesktop: false,
      expanded: false,
      separator: false,
      loading: false,
      type: 4,
    },
    {
      label: 'My Account',
      name: 'myAccount',
      url: '/my-account',
      subMenus: [
        {
          label: 'Switch Customer',
          url: '',
          name: 'switchCustomer',
          isClick: true,
        },
        { label: 'My Account', url: '/my-account' },
        { label: 'Customer Centre', url: '/customer-center' },
        { label: 'Contact Us', url: '/contact' },
        { label: 'Log Off', url: '/logout' },
      ],
      isDesktop: true,
      isMobile: false,
      expanded: false,
      separator: false,
      loading: false,
      type: 4,
    },
    {
      label: 'Contact',
      name: 'contact',
      url: '/contact',
      subMenus: [],
      isMobile: true,
      isDesktop: false,
      expanded: false,
      separator: false,
      loading: false,
      type: 5,
    },
    {
      label: 'Customer Centre',
      name: 'customerCentre',
      url: '/customer-center',
      subMenus: [],
      isMobile: true,
      isDesktop: false,
      expanded: false,
      separator: false,
      loading: false,
      type: 6,
    },
  ],
};
