// Mutations enums
export enum MutationTypes {
  SET_PRODUCTS = 'SET_PRODUCTS',
  RESET_PRODUCTS = 'RESET_PRODUCTS',
  SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS',
  UPDATE_FAVOURITE = 'UPDATE_FAVOURITE',
  UPDATE_PRODUCT_STOCK = 'UPDATE_PRODUCT_STOCK',
  UPDATE_PRODUCT_MULTIPLE_STOCK = 'UPDATE_PRODUCT_MULTIPLE_STOCK',
  UPDATE_SOH_BY_UNIT = 'UPDATE_SOH_BY_UNIT',
}
